services:
  - type: web
    name: eam-collaboration-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 8080
      - key: MYSQLHOST
        value: containers-us-west-23.railway.app
      - key: MYSQLPORT
        value: 3306
      - key: MYSQLUSER
        value: root
      - key: MYSQLPASSWORD
        value: BOkAAnlcySxAodeKLGciQlHlBCcopuHl
      - key: MYSQLDATABASE
        value: railway
      - key: JWT_SECRET
        value: your_secret_key
